//
//  ListModels.swift
//  Containment
//
//  Created by Raymond Law on 8/28/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List
{
  // MARK: Use cases
  
  enum FetchOrders
  {
    struct Request
    {
      var sortBy: Order.SortBy = Order.SortBy.date
    }
    struct Response
    {
      var orders: [Order]
    }
    struct ViewModel
    {
      struct Order
      {
        var date: String
        var total: String
      }
      var orders: [Order]
    }
  }
  
  enum GetOrder
  {
    struct Request
    {
      var index: Int
    }
    struct Response
    {
      var order: Order
    }
    struct ViewModel
    {
      var order: Order
    }
  }
}
