//
//  DetailInteractor.swift
//  Containment
//
//  Created by Raymond Law on 8/28/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func showOrder(request: Detail.ShowOrder.Request)
}

protocol DetailDataStore
{
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?
  
  // MARK: Show order
  
  func showOrder(request: Detail.ShowOrder.Request)
  {
    let response = Detail.ShowOrder.Response(order: request.order)
    presenter?.presentOrder(response: response)
  }
}
