//
//  SortPresenter.swift
//  Containment
//
//  Created by Raymond Law on 8/28/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SortPresentationLogic
{
  func presentSortedOrders(response: Sort.SortOrders.Response)
}

class SortPresenter: SortPresentationLogic
{
  weak var viewController: SortDisplayLogic?
  
  // MARK: Sort orders
  
  func presentSortedOrders(response: Sort.SortOrders.Response)
  {
//    let viewModel = Sort.SortOrders.ViewModel()
//    viewController?.displaySortedOrders(viewModel: viewModel)
  }
}
