//
//  SortInteractor.swift
//  Containment
//
//  Created by Raymond Law on 8/28/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SortBusinessLogic
{
  func sortOrders(request: Sort.SortOrders.Request)
}

protocol SortDataStore
{
}

class SortInteractor: SortBusinessLogic, SortDataStore
{
  var presenter: SortPresentationLogic?
  var worker: SortWorker?
  
  // MARK: Sort orders
  
  func sortOrders(request: Sort.SortOrders.Request)
  {
//    let response = Sort.SortOrders.Response()
//    presenter?.presentSortedOrders(response: response)
  }
}
